_target_: alpamayo1_5_sft.models.sft_base_model.TrainableReasoningVLA.from_alpamayo_checkpoint
checkpoint_path: /data/wesleyferreiramaia/wokzone-alpamayo/checkpoints/sft_stage4_student/checkpoint-3000
vlm_name_or_path: /data/wesleyferreiramaia/wokzone-alpamayo/models/Cosmos-Reason2-2B
