_target_: alpamayo1_5_sft.models.sft_base_model.TrainableReasoningVLA.from_alpamayo_checkpoint
checkpoint_path: /data/wesleyferreiramaia/wokzone-alpamayo/models/Alpamayo-1.5-10B-A1-format
vlm_name_or_path: /data/wesleyferreiramaia/wokzone-alpamayo/models/Cosmos-Reason2-8B
